name: my react app
run-name: ${{github.actor}} is testing out GitHub Actions
on:
  push: 
    branches:
      - main

jobs:
  Explore-GitHub-Acctions:
    runs-on: ubuntu-latest
    steps:
      - name: echo the message
        run:  echo "Hi Adonis"
        
      - name: npm install
        run: npm i
