name: Deploying My React App
run-name: ${{github.actor}} is testing out GitHub Actions

on:
  push: 
    branches:
      - main

jobs:
  Explore-GitHub-Acctions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

